#!/bin/bash
# Checks that Ctrl-C during `saga dev` always kills its children.
#
# Child processes get their own process group, so a SIGINT the CLI doesn't
# handle itself reaches only the CLI and leaves children running under launchd.
# Each scenario interrupts at a different point in the CLI's lifecycle and then
# asserts nothing survived.
#
# Usage: IntegrationTests/run-shutdown-tests.sh [port]

set -u
set -m   # job control, so background children don't inherit SIGINT=SIG_IGN

ROOT=$(cd "$(dirname "$0")/.." && pwd)
FIXTURE=$ROOT/IntegrationTests/Fixture
SAGA=$ROOT/.build/debug/saga
PORT=${1:-3999}
LOG=$(mktemp)

fail() { echo "error: $*" >&2; exit 1; }

[ -x "$SAGA" ] || fail "$SAGA not found, run 'swift build' first"

# A file big enough that rebuilding it takes long enough to interrupt.
mkdir -p "$FIXTURE/Sources/Fixture" "$FIXTURE/content" "$FIXTURE/deploy"
echo "<html>fixture</html>" > "$FIXTURE/deploy/index.html"
python3 -c "
print('// generated by run-shutdown-tests.sh')
for i in range(6000): print(f'func slowFunc{i}(_ x: Int) -> Int {{ x &+ {i} }}')
" > "$FIXTURE/Sources/Fixture/Generated.swift" || fail "could not generate fixture source"

(cd "$FIXTURE" && swift build) > /dev/null 2>&1 || fail "fixture failed to build"

reset() {
  pkill -f "saga dev --port $PORT" 2>/dev/null
  pkill -f "Fixture/.build/debug/Fixture" 2>/dev/null
  sleep 0.5
}

# $1 = label, $2 = point to interrupt at
scenario() {
  local label=$1 when=$2
  reset
  cd "$FIXTURE" || exit 1
  if [ "$when" = startup ]; then export FIXTURE_HANG=1; else unset FIXTURE_HANG; fi
  [ "$when" = initial-build ] && touch "$FIXTURE/Sources/Fixture/Generated.swift"

  "$SAGA" dev --port "$PORT" > "$LOG" 2>&1 &
  local dev=$! site= build=

  case $when in
    product-lookup)
      for _ in $(seq 1 100); do build=$(pgrep -P $dev -f "dump-package" | head -1); [ -n "$build" ] && break; sleep 0.05; done
      ;;
    initial-build)
      for _ in $(seq 1 200); do build=$(pgrep -P $dev -f "swift-build|swift build" | head -1); [ -n "$build" ] && break; sleep 0.05; done
      ;;
    startup)
      for _ in $(seq 1 200); do site=$(pgrep -P $dev -f "debug/Fixture" | head -1); [ -n "$site" ] && break; sleep 0.1; done
      ;;
    idle|recompile)
      for _ in $(seq 1 300); do
        lsof -nP -iTCP:"$PORT" -sTCP:LISTEN -t 2>/dev/null | grep -qx "$dev" && break
        sleep 0.1
      done
      site=$(pgrep -P $dev -f "debug/Fixture" | head -1)
      if [ "$when" = recompile ]; then
        touch "$FIXTURE/Sources/Fixture/Generated.swift"
        kill -USR1 $dev
        for _ in $(seq 1 100); do
          build=$(pgrep -P $dev | grep -v "^$site\$" | head -1); [ -n "$build" ] && break; sleep 0.05
        done
      fi
      ;;
  esac

  kill -INT $dev 2>/dev/null
  wait $dev 2>/dev/null
  sleep 1

  local bad=0 detail=""
  kill -0 $dev 2>/dev/null && { detail="$detail cli-still-running"; bad=1; }
  [ -n "$site"  ] && kill -0 "$site"  2>/dev/null && { detail="$detail site-orphaned"; bad=1; }
  [ -n "$build" ] && kill -0 "$build" 2>/dev/null && { detail="$detail build-orphaned"; bad=1; }
  lsof -nP -iTCP:"$PORT" -sTCP:LISTEN -t >/dev/null 2>&1 && { detail="$detail port-still-open"; bad=1; }
  grep -q "Shutting down" "$LOG" || { detail="$detail no-shutdown-handler"; bad=1; }

  # An empty pid means the scenario never caught the process it meant to
  # interrupt, so a pass would prove nothing.
  case $when in
    product-lookup|initial-build|recompile) [ -z "$build" ] && { detail="$detail never-observed-build"; bad=1; } ;;
    startup|idle)                           [ -z "$site"  ] && { detail="$detail never-observed-site";  bad=1; } ;;
  esac

  if [ $bad -eq 0 ]; then
    printf "  ok    %-22s (site=%s build=%s)\n" "$label" "${site:--}" "${build:--}"
  else
    printf "  FAIL  %-22s%s\n" "$label" "$detail"
  fi
  reset
  return $bad
}

echo "Ctrl-C during \`saga dev\` (port $PORT)"
rc=0
scenario "product lookup" product-lookup || rc=1
scenario "initial build"  initial-build  || rc=1
scenario "startup window" startup        || rc=1
scenario "idle"           idle           || rc=1
scenario "recompile"      recompile      || rc=1

rm -f "$LOG"
[ $rc -eq 0 ] && echo "All shutdown tests passed." || echo "Shutdown tests failed."
exit $rc
